# SPDX-License-Identifier: GPL-3.0-only
# MuseScore-Studio-CLA-applies
#
# MuseScore Studio
# Music Composition & Notation
#
# Copyright (C) 2026 MuseScore Limited
#
# License and notice installation for the files that are shipped to users.
#
# Every notice is copied verbatim from the tree that actually produced the shipped
# binary: the pinned dependency payload for fetched dependencies, the vendored source
# directory for in-tree third party, or a pinned notice payload for components whose
# own archive carries no notice (see buildscripts/cmake/deps/license_notices.cmake).
# A missing notice file is a configure error, so an install tree can never be built
# with a silently incomplete notice set.
#
# The destination is <resources>/licenses/<name>, next to the other resource
# directories (sound, styles, templates, locale).

include_guard()

# muse_install_license_notice(<name> <source-dir> <relative-file>...)
#
# The optional <subdir> argument is spelled as part of the relative path, so a
# dependency that keeps several notice files apart (for example common/LICENSE.txt
# and LICENSE.txt) keeps that structure in the install tree.
function(muse_install_license_notice name source_dir)
    if (NOT MUSE_APP_INSTALL_RESOURCES_LOCATION)
        message(FATAL_ERROR
            "[licenses] MUSE_APP_INSTALL_RESOURCES_LOCATION is not set; cannot install the "
            "${name} notices.")
    endif()

    set(destination "${MUSE_APP_INSTALL_RESOURCES_LOCATION}/licenses/${name}")
    set(missing "")
    foreach (relative IN LISTS ARGN)
        if (NOT EXISTS "${source_dir}/${relative}")
            list(APPEND missing "${relative}")
        endif()
    endforeach()

    if (missing)
        message(FATAL_ERROR
            "[licenses] ${name}: notice file(s) ${missing} were not found under '${source_dir}'. "
            "The pinned payload or the vendored source changed; update the notice set instead of "
            "shipping an incomplete license directory.")
    endif()

    foreach (relative IN LISTS ARGN)
        get_filename_component(file_name "${relative}" NAME)
        get_filename_component(file_dir "${relative}" DIRECTORY)
        if (file_dir)
            install(FILES "${source_dir}/${relative}"
                DESTINATION "${destination}/${file_dir}")
        else()
            install(FILES "${source_dir}/${relative}"
                DESTINATION "${destination}")
        endif()
        message(STATUS "[licenses] ${name}: ${file_name}")
    endforeach()
endfunction()

# muse_install_qt_attribution(<qt-install-prefix>)
#
# The Qt license texts alone are not attribution. The installed Qt modules carry their
# attribution metadata (qt_attribution.json and REUSE.toml, generated by Qt's own
# qtattributionsscanner) next to the CMake and share files, so the exact set the shipped
# kit contains is installed verbatim. Finding none is a configure error: it would mean
# shipping Qt with no attribution at all.
function(muse_install_qt_attribution qt_install_prefix)
    if (NOT MUSE_APP_INSTALL_RESOURCES_LOCATION)
        message(FATAL_ERROR
            "[licenses] MUSE_APP_INSTALL_RESOURCES_LOCATION is not set; cannot install the "
            "Qt attribution metadata.")
    endif()
    if (NOT IS_DIRECTORY "${qt_install_prefix}")
        message(FATAL_ERROR
            "[licenses] the Qt install prefix '${qt_install_prefix}' is not a directory; "
            "cannot install the Qt attribution metadata.")
    endif()

    file(GLOB_RECURSE _attribution LIST_DIRECTORIES FALSE
        "${qt_install_prefix}/lib/cmake/*/qt_attribution.json"
        "${qt_install_prefix}/lib/cmake/*/REUSE.toml"
        "${qt_install_prefix}/share/qt6/*/qt_attribution.json"
        "${qt_install_prefix}/share/qt6/*/REUSE.toml"
    )
    list(LENGTH _attribution _count)
    if (_count EQUAL 0)
        message(FATAL_ERROR
            "[licenses] no Qt attribution metadata (qt_attribution.json / REUSE.toml) was found "
            "under '${qt_install_prefix}'. The shipped Qt kit changed; update the notice set "
            "instead of shipping Qt without attribution.")
    endif()

    foreach (_file IN LISTS _attribution)
        file(RELATIVE_PATH _relative "${qt_install_prefix}" "${_file}")
        get_filename_component(_directory "${_relative}" DIRECTORY)
        install(FILES "${_file}"
            DESTINATION "${MUSE_APP_INSTALL_RESOURCES_LOCATION}/licenses/qt-attribution/${_directory}")
    endforeach()
    message(STATUS "[licenses] qt-attribution: ${_count} attribution file(s)")
endfunction()

# muse_install_source_index(<path>|<note>...)
#
# Writes licenses/SOURCE-REFS.txt so the artifact carries the exact sources of the
# components whose notices it ships: every pinned payload archive with its SHA-256, plus
# the vendored directories compiled into the binary. The application and framework
# revisions are recorded in the package manifest and in provenance.json.
function(muse_install_source_index)
    if (NOT MUSE_APP_INSTALL_RESOURCES_LOCATION)
        message(FATAL_ERROR
            "[licenses] MUSE_APP_INSTALL_RESOURCES_LOCATION is not set; cannot install the "
            "source reference index.")
    endif()

    set(content "MuseScore Studio fork release: license and notice source index\n")
    string(APPEND content "Generated at configure time from buildscripts/cmake/deps/dependencies.lock.cmake.\n")
    string(APPEND content "\nPinned payload archives (dependency, directory, URL, SHA-256):\n")

    get_cmake_property(_variables VARIABLES)
    foreach (_variable IN LISTS _variables)
        if (_variable MATCHES "^MUSE_DEP_(.+)_PAYLOADS$")
            set(_dependency "${CMAKE_MATCH_1}")
            foreach (_entry IN LISTS ${_variable})
                if (_entry MATCHES "^single-root\\|([^|]+)\\|([^|]+)\\|([0-9a-f]+)$")
                    string(APPEND content "  ${_dependency}  ${CMAKE_MATCH_1}  ${CMAKE_MATCH_2}  ${CMAKE_MATCH_3}\n")
                endif()
            endforeach()
        endif()
    endforeach()

    string(APPEND content "\nVendored third party compiled into the shipped binary:\n")
    foreach (_pair IN LISTS ARGN)
        string(REPLACE "|" "  " _line "${_pair}")
        string(APPEND content "  ${_line}\n")
    endforeach()

    string(APPEND content "\nQt 6.10.2: license texts from the pinned qtbase source archive above; the Qt binary\n")
    string(APPEND content "packages carry no license texts. Application and framework sources are the revisions\n")
    string(APPEND content "recorded in build-manifest.json and provenance.json for this build.\n")

    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/SOURCE-REFS.txt" "${content}")
    install(FILES "${CMAKE_CURRENT_BINARY_DIR}/SOURCE-REFS.txt"
        DESTINATION "${MUSE_APP_INSTALL_RESOURCES_LOCATION}/licenses")
    message(STATUS "[licenses] source index: ${CMAKE_CURRENT_BINARY_DIR}/SOURCE-REFS.txt")
endfunction()

# muse_install_license_tree(<name> <source-dir> <relative-dir> <glob>)
#
# Installs every file matching <glob> under <relative-dir> (used for the Qt license
# text set, which is a directory of REUSE-style texts rather than a single file).
function(muse_install_license_tree name source_dir relative_dir pattern)
    set(from "${source_dir}/${relative_dir}")
    if (NOT IS_DIRECTORY "${from}")
        message(FATAL_ERROR
            "[licenses] ${name}: notice directory '${from}' is missing. "
            "The pinned payload changed; update the notice set instead of shipping an "
            "incomplete license directory.")
    endif()

    file(GLOB notice_files "${from}/${pattern}")
    list(LENGTH notice_files notice_count)
    if (notice_count EQUAL 0)
        message(FATAL_ERROR
            "[licenses] ${name}: no notice matched '${pattern}' under '${from}'.")
    endif()

    install(FILES ${notice_files}
        DESTINATION "${MUSE_APP_INSTALL_RESOURCES_LOCATION}/licenses/${name}")
    message(STATUS "[licenses] ${name}: ${notice_count} notice file(s)")
endfunction()
